<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Classroom_ctl00ContentPlaceHolder1RadGridRoomsPagectl00ctl04RoomInventoryReportImageButton</name>
   <tag></tag>
   <elementGuidId>090cfdad-43a3-48f4-ae46-ae7811bec434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00_ctl04_RoomInventoryReportImageButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00_ctl04_RoomInventoryReportImageButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadGridRoomsPage$ctl00$ctl04$RoomInventoryReportImageButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00_ctl04_RoomInventoryReportImageButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room Inventory Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Report.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room Inventory Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:GenerateReport('EntityInventoryReport','{&quot;EntityUID&quot;:62271,&quot;EntityUIDs&quot;:null,&quot;EntityTypeUID&quot;:2,&quot;FilterExpression&quot;:&quot;&quot;,&quot;ReportField&quot;:0,&quot;includeDistrictSummary&quot;:false,&quot;IncludeUntaggedInventory&quot;:false,&quot;ReportNotes&quot;:null,&quot;FilterByToday&quot;:false,&quot;Active&quot;:&quot;True&quot;,&quot;PreviewTagReport&quot;:false,&quot;Line1Text&quot;:null,&quot;Line2Text&quot;:null,&quot;TagLabelLetter&quot;:null,&quot;StartingTagNumber&quot;:0,&quot;LabelCount&quot;:0,&quot;TopMarginOffset&quot;:0,&quot;BottomMarginOffset&quot;:0,&quot;LeftMarginOffset&quot;:0,&quot;RightMarginOffset&quot;:0,&quot;TransferNumber&quot;:0,&quot;ChargeUID&quot;:0,&quot;SiteID&quot;:null,&quot;SiteUID&quot;:0,&quot;AuditDetailUID&quot;:0,&quot;ShowFullCatalog&quot;:false,&quot;Received&quot;:null,&quot;ContainerUID&quot;:0,&quot;SelectedSites&quot;:null,&quot;SelectedStatus&quot;:null,&quot;IncludeDistrictTotals&quot;:false,&quot;PurchaseItemShipmentUID&quot;:0,&quot;ShippedToSiteUID&quot;:0,&quot;IncludeStaffInventory&quot;:false,&quot;FullChargeReceiptSortOrder&quot;:0,&quot;FullChargeReceiptIncludeSatisfiedCharges&quot;:false,&quot;AuditUID&quot;:0,&quot;SiteApproveAudits&quot;:null,&quot;DisplayProductImages&quot;:false,&quot;AuditPercentStatus&quot;:null,&quot;ActiveDepartments&quot;:null,&quot;UserID&quot;:3,&quot;AssignedDepartments&quot;:null,&quot;DistrictName&quot;:null,&quot;PurchaseItemShipmenArgs&quot;:null,&quot;ImagePath&quot;:null,&quot;SignaturePath&quot;:null,&quot;UserRole&quot;:null,&quot;Filters&quot;:null,&quot;Filtered&quot;:null,&quot;BasicFilters&quot;:null,&quot;AdvancedFilters&quot;:null,&quot;InventoryHistoryUID&quot;:0,&quot;TIPWebUserReportUID&quot;:0,&quot;ShowReport&quot;:false,&quot;FileName&quot;:null,&quot;UserRoleUID&quot;:0,&quot;SortOrders&quot;:null}'); return false;WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$RadGridRoomsPage$ctl00$ctl04$RoomInventoryReportImageButton&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00_ctl04_RoomInventoryReportImageButton&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00_ctl04_RoomInventoryReportImageButton']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridRoomsPage_ctl00__0']/td[8]/input[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input[3]</value>
   </webElementXpaths>
</WebElementEntity>
