<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Complete_ctl00ContentPlaceHolder1RadGridTransferHistoryctl00ctl04PrintReport</name>
   <tag></tag>
   <elementGuidId>2b4207a7-935e-404c-aede-6d3f8a8509ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00__0']/td[9]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport&quot;)[count(. | //input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$RadGridTransferHistory$ctl00$ctl04$PrintReport' and @id = 'ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport' and @title = 'Print Transfer Report' and @src = '../App_Themes/TIPWeb/Images/Report.gif' and @alt = 'Quick Transfer Report' and @onclick = 'return Refresh();' and @align = 'middle' and @ref_element = 'Object Repository/TIPWeb-IT/Print Transfer/Page_TIPWeb-IT Version 10.5.4.0/iframe_Close_RadWindowTransferHistory']) = count(//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$RadGridTransferHistory$ctl00$ctl04$PrintReport' and @id = 'ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport' and @title = 'Print Transfer Report' and @src = '../App_Themes/TIPWeb/Images/Report.gif' and @alt = 'Quick Transfer Report' and @onclick = 'return Refresh();' and @align = 'middle' and @ref_element = 'Object Repository/TIPWeb-IT/Print Transfer/Page_TIPWeb-IT Version 10.5.4.0/iframe_Close_RadWindowTransferHistory'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadGridTransferHistory$ctl00$ctl04$PrintReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Print Transfer Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Report.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Quick Transfer Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return Refresh();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWeb-IT/Print Transfer/iframe_Close_RadWindowTransferHistory</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00_ctl04_PrintReport']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridTransferHistory_ctl00__0']/td[9]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
