<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loading Spinner</name>
   <tag></tag>
   <elementGuidId>8159624f-ff5f-4de4-aaa4-671aaff5330b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Loading'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadDock4_C > div.block-overlay > img[alt=&quot;Loading&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b121a5b4-7bd0-43af-a686-2b408742f167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Loading</value>
      <webElementGuid>bd181c5f-afa0-4d1f-8b8f-d3adba49de88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Loading</value>
      <webElementGuid>12a7466a-9038-4796-be09-9d919f1c0093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>App_Themes/TipWeb/Common/loading.gif</value>
      <webElementGuid>c0b79447-ebf9-41e6-a6b2-32012bcbd4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadDock4_C&quot;)/div[@class=&quot;block-overlay&quot;]/img[1]</value>
      <webElementGuid>141104db-0fde-42e9-900a-7eaaf4a12d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadDock4_C']/div/img</value>
      <webElementGuid>2761c183-da80-4a38-a8f7-477fb8f6a593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Loading'])[4]</value>
      <webElementGuid>8e0b29b8-e0fd-4259-ab2c-01eec0f77f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>36fb80c2-f82c-4ed9-b38a-3d309914e77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Loading' and @title = 'Loading' and @src = 'App_Themes/TipWeb/Common/loading.gif']</value>
      <webElementGuid>9d781be2-34b3-4a41-899a-7b24aa461884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
