<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New_ctl00ContentPlaceHolder1RadGridDistrictAuditDetailsctl00ctl04ImageButtonEntityAuditSummaryReport</name>
   <tag></tag>
   <elementGuidId>27eff695-b1de-4f3a-9b05-7768f816e808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00_ctl04_ImageButtonEntityAuditSummaryReport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00_ctl04_ImageButtonEntityAuditSummaryReport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadGridDistrictAuditDetails$ctl00$ctl04$ImageButtonEntityAuditSummaryReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00_ctl04_ImageButtonEntityAuditSummaryReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room Audit Summary Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Report.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Audit Summary Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:parent.GenerateReport('EntityAuditSummaryReport','{&quot;EntityUID&quot;:0,&quot;EntityUIDs&quot;:null,&quot;EntityTypeUID&quot;:2,&quot;FilterExpression&quot;:null,&quot;ReportField&quot;:0,&quot;includeDistrictSummary&quot;:false,&quot;IncludeUntaggedInventory&quot;:false,&quot;ReportNotes&quot;:null,&quot;FilterByToday&quot;:false,&quot;Active&quot;:null,&quot;PreviewTagReport&quot;:false,&quot;Line1Text&quot;:null,&quot;Line2Text&quot;:null,&quot;TagLabelLetter&quot;:null,&quot;StartingTagNumber&quot;:0,&quot;LabelCount&quot;:0,&quot;TopMarginOffset&quot;:0,&quot;BottomMarginOffset&quot;:0,&quot;LeftMarginOffset&quot;:0,&quot;RightMarginOffset&quot;:0,&quot;TransferNumber&quot;:0,&quot;ChargeUID&quot;:0,&quot;SiteID&quot;:null,&quot;SiteUID&quot;:0,&quot;AuditDetailUID&quot;:760494,&quot;ShowFullCatalog&quot;:false,&quot;Received&quot;:null,&quot;ContainerUID&quot;:0,&quot;SelectedSites&quot;:null,&quot;SelectedStatus&quot;:null,&quot;IncludeDistrictTotals&quot;:false,&quot;PurchaseItemShipmentUID&quot;:0,&quot;ShippedToSiteUID&quot;:0,&quot;IncludeStaffInventory&quot;:false,&quot;FullChargeReceiptSortOrder&quot;:0,&quot;FullChargeReceiptIncludeSatisfiedCharges&quot;:false,&quot;AuditUID&quot;:0,&quot;SiteApproveAudits&quot;:null,&quot;DisplayProductImages&quot;:false,&quot;AuditPercentStatus&quot;:null,&quot;ActiveDepartments&quot;:null,&quot;UserID&quot;:3,&quot;AssignedDepartments&quot;:[0,1,2,3,4,5,6,7,8,9,14,16],&quot;DistrictName&quot;:null,&quot;PurchaseItemShipmenArgs&quot;:null,&quot;ImagePath&quot;:null,&quot;SignaturePath&quot;:null,&quot;UserRole&quot;:null,&quot;Filters&quot;:null,&quot;Filtered&quot;:null,&quot;BasicFilters&quot;:null,&quot;AdvancedFilters&quot;:null,&quot;InventoryHistoryUID&quot;:0,&quot;TIPWebUserReportUID&quot;:0,&quot;ShowReport&quot;:false,&quot;FileName&quot;:null,&quot;UserRoleUID&quot;:0,&quot;SortOrders&quot;:null}');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00_ctl04_ImageButtonEntityAuditSummaryReport&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TIPWeb-IT/Page_TIPWeb-IT Version 10.5.4.0/iframe_Close_RadWindowDistrictAuditDetails</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00_ctl04_ImageButtonEntityAuditSummaryReport']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridDistrictAuditDetails_ctl00__0']/td[10]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
