<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Record</name>
   <tag></tag>
   <elementGuidId>bcd4471a-8c73-40a2-ba07-cd176443a984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddRecordLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AddRecordLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2d15c33-92f5-4d88-8ef7-e76246e90e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenWindowNav('AuditManagement/InitiateAudit.aspx','RadWindowInitiateAudit'); return false;</value>
      <webElementGuid>927e2651-01dd-4896-951e-54147d5b5b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddRecordLink</value>
      <webElementGuid>1f3cb41d-a628-425c-98b7-091de2102a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Initiate Site Audit</value>
      <webElementGuid>8458e493-243a-43d7-b459-7f0542e2ff6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridSiteAudits$ctl00$ctl02$ctl00$AddRecordLink','')</value>
      <webElementGuid>961be06d-9f6b-4ebc-98cb-29d900c7ad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>b7c55b96-b065-4f8d-bf7c-776b5b7c4fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddRecordLink&quot;)</value>
      <webElementGuid>75f78fef-e57c-4151-8279-72d709e88278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AddRecordLink']</value>
      <webElementGuid>b3176e54-5c73-4470-9794-c668cdc1b30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridSiteAudits_ctl00']/thead/tr/td/div/div/a</value>
      <webElementGuid>34b8aab3-c2b4-495b-ad96-97b2f8ee8ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Record')]</value>
      <webElementGuid>7da735f0-bb3d-42bc-ab7d-b1314175251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Set'])[2]/following::a[1]</value>
      <webElementGuid>73b40db0-6cb3-44ec-8920-08a702bfc812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Required'])[1]/following::a[1]</value>
      <webElementGuid>c74f2b62-fa59-471e-b87f-be4896ccc967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Columns'])[1]/preceding::a[1]</value>
      <webElementGuid>3208f2fc-da07-4342-b236-f580a1971463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail Compliance Report'])[1]/preceding::a[2]</value>
      <webElementGuid>5d2e4142-c858-489f-9e4c-582890d53b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Record']/parent::*</value>
      <webElementGuid>04089075-9eee-4296-989b-06fab5b18c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridSiteAudits$ctl00$ctl02$ctl00$AddRecordLink','')&quot;)]</value>
      <webElementGuid>0fbe354a-ba5f-4f2b-932e-a5526977b51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/a</value>
      <webElementGuid>d47cf57c-3379-4116-b610-7e32e6f55431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AddRecordLink' and @title = 'Initiate Site Audit' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$RadGridSiteAudits$ctl00$ctl02$ctl00$AddRecordLink&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Add Record' or . = 'Add Record')]</value>
      <webElementGuid>b3e566d0-4c13-4e22-8e45-dbb73c39b66d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
