<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_select_1</name>
   <tag></tag>
   <elementGuidId>0370940e-f345-4eb6-9185-12f239cfe0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d4ceb01-a12f-4f7a-a6d2-47601fb6d609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow</value>
      <webElementGuid>51b81097-3211-453e-935b-af3a69e1d3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e965784-d5a0-47ed-a794-a84f92e08dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow&quot;)</value>
      <webElementGuid>6c8f9287-950d-4210-918b-b1e499a1c0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow']</value>
      <webElementGuid>f03abe77-9b4e-4b07-8a06-2706624f2fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>73adbe10-d87f-46b7-a397-afaf07bd8e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'select')])[14]</value>
      <webElementGuid>ec8528c6-0457-40dd-9566-3782fe74f8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[3]/following::a[1]</value>
      <webElementGuid>9590c69c-c66b-4136-93b8-cefbf035cfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Type:'])[1]/following::a[1]</value>
      <webElementGuid>737a7150-c8e0-47e6-a198-70f3476e2f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check All'])[5]/preceding::a[1]</value>
      <webElementGuid>e860f911-3bd3-4e82-ba49-dafedc467a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auctioned'])[3]/preceding::a[1]</value>
      <webElementGuid>885b85d1-3568-4b6e-b09b-ca6d7ebc562c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>0bcbc673-2637-429c-9cd5-07d2c36a27e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Arrow' and (text() = 'select' or . = 'select')]</value>
      <webElementGuid>da1b3c3f-a31a-4aca-9255-3baafa079925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
