<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site Name_ctl00ContentPlaceHolder1Rad_6b4b20</name>
   <tag></tag>
   <elementGuidId>25e813a4-aefb-445c-a66e-cc06e2c91ae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aa29f0b-4026-492f-92fd-0fc1d31181d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxSiteNameFilter</value>
      <webElementGuid>29de4a5c-669b-4562-bdda-464488c0f2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a527bfb2-c292-47d5-9d12-2145f1e9ce38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>f4e9c6f1-275f-4b67-9144-80dfa9566954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input</value>
      <webElementGuid>fa4588aa-d9d8-437c-a1d2-c255d663bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Please select:</value>
      <webElementGuid>fd68054a-c364-4217-9670-a995d6acd583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7a194c23-b3ea-46c7-ae12-fd9600c73206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ff6d69b-eb99-48c1-a6f8-3da3098548f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input&quot;)</value>
      <webElementGuid>db5e201d-4d46-4ff5-a0f4-571d728b91d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      <webElementGuid>348b0d14-1021-4069-a747-ff131b07bd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter']/table/tbody/tr/td/input</value>
      <webElementGuid>3de8978b-4731-4860-84a7-a6244a6d1ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>99d0f2d9-9c99-4a75-8376-1c2e31f138fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxSiteNameFilter' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      <webElementGuid>80f7338f-9752-43e7-96a9-358a59cd0293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
