<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor_ctl00ContentPlaceHolder1ImageButtonGo</name>
   <tag></tag>
   <elementGuidId>93c8e7fa-5b77-4eab-a403-462bf21a7e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8098e6f1-f5db-46be-becb-57bd98ab0a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>72e8e2b0-db0f-405b-8090-48281380e7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ImageButtonGo</value>
      <webElementGuid>ee135ff9-2936-4a44-89be-5de84722d946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      <webElementGuid>4e4d3516-899b-4d95-9b3f-647ab744c106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e128151a-08f8-4c6f-a645-e137d4a41c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>1031c4a9-07cc-4528-b044-5085961e53ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWEB/Images/go.gif</value>
      <webElementGuid>2eaa482f-fbc9-43fd-8c40-c9f66ca23b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>31dd510c-3939-4285-a9ea-df31b6c08dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidateTagFilters();</value>
      <webElementGuid>5cb8251b-7ad7-40ca-a14c-f4b5521f69b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ImageButtonGo&quot;)</value>
      <webElementGuid>2a10feb1-37b5-46b3-9dea-9c1051f73e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      <webElementGuid>efafd40f-6ac9-4371-b896-c626fc94b7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_FiltersPanel']/div[2]/input[2]</value>
      <webElementGuid>db0b1ef6-5aa9-4275-8d6c-3147c99a3cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input[2]</value>
      <webElementGuid>46a22378-5ee6-45bd-9137-9c27e710781b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$ImageButtonGo' and @id = 'ctl00_ContentPlaceHolder1_ImageButtonGo' and @title = 'Apply Filter(s)' and @src = '../App_Themes/TIPWEB/Images/go.gif' and @alt = 'Apply Filter(s)']</value>
      <webElementGuid>763c3dc7-ede4-4b3b-924b-13938d18fcb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
