<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Record</name>
   <tag></tag>
   <elementGuidId>a5e6e50d-9b5f-4412-b21f-89fc8b05f6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7e246f3-0618-4e96-bbbc-cc5c0efe76af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord</value>
      <webElementGuid>541a3925-5e7f-4e00-8b93-c80a3f2a4bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridSites$ctl00$ctl02$ctl00$LinkButtonAddRecord','')</value>
      <webElementGuid>f24d3b1d-7e57-44f4-97cc-94bb549baaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>d59e71e9-ad9e-46fb-b7e8-323d6b58f438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord&quot;)</value>
      <webElementGuid>2d8f2b7a-5dd2-4f6a-a0a2-4ab38445a6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord']</value>
      <webElementGuid>aff9313f-588b-4157-9b45-d62b3d177864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridSites_ctl00']/thead/tr/td/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>5c78daba-342b-4b3f-b499-9aa7f2885407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Record')]</value>
      <webElementGuid>9abacc06-19f7-4f87-9ace-970150685f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Off'])[1]/following::a[1]</value>
      <webElementGuid>608890c6-e01a-446a-b0c6-81c49c39e11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Inactive'])[1]/preceding::a[1]</value>
      <webElementGuid>0260a1b6-1c0c-45e9-b822-09105d938fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[2]/preceding::a[2]</value>
      <webElementGuid>5ff0604c-dd00-475a-b751-bc397d49e6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Record']/parent::*</value>
      <webElementGuid>1768a08f-a888-499c-aa36-248b270180be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridSites$ctl00$ctl02$ctl00$LinkButtonAddRecord','')&quot;)]</value>
      <webElementGuid>06be6f7e-aeef-4a0b-bf48-e0dff1d204c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>6b5913f2-88fd-48bf-94c6-46434f65bb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadGridSites_ctl00_ctl02_ctl00_LinkButtonAddRecord' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$RadGridSites$ctl00$ctl02$ctl00$LinkButtonAddRecord&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Add Record' or . = 'Add Record')]</value>
      <webElementGuid>9abbdf74-1fbc-4b9e-82e4-e6254e2cdae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
