<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Off</name>
   <tag></tag>
   <elementGuidId>631d48de-037b-4ea1-9d3d-5464b1859e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rmScrollWrap.rmGroup.rmLevel1 > ul.rmVertical > li.rmItem.rmLast > a.rmLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36e1b1ba-7be6-49f3-bd48-cdfba2afc2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink</value>
      <webElementGuid>a40ba387-a98a-49a8-8381-1870a96d388b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>be04b151-7bb6-4257-bad7-cb05f5cbcfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Off</value>
      <webElementGuid>3a055dce-6c50-48a8-ad89-2cb1e379de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_RadMenuUserOptions&quot;)/ul[@class=&quot;rmRootGroup rmToggleHandles rmHorizontal&quot;]/li[@class=&quot;rmItem rmFirst rmLast&quot;]/div[@class=&quot;rmSlide&quot;]/div[@class=&quot;rmScrollWrap rmGroup rmLevel1&quot;]/ul[@class=&quot;rmVertical&quot;]/li[@class=&quot;rmItem rmLast&quot;]/a[@class=&quot;rmLink&quot;]</value>
      <webElementGuid>2f60c8b8-da79-47e2-99d7-f5f72e79282a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/div/div/ul/li[2]/a</value>
      <webElementGuid>9bcbf1b7-d8f3-4bc7-8472-70acef78d068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/following::a[1]</value>
      <webElementGuid>2d5484fa-b8b0-4803-ae61-04487c9bc84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle'])[1]/following::a[2]</value>
      <webElementGuid>e3cfc9a2-e5ca-4932-ab14-24a55ad8d336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>a18d722c-2621-4721-b17d-ff331e471a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/ul/li[2]/a</value>
      <webElementGuid>3ad85591-0178-4207-8798-6270c688ab90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
