<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toggle</name>
   <tag></tag>
   <elementGuidId>01b7e8ae-19b5-4ff1-8c06-5c03ac6d7e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/a/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.rmIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>873c65fd-5f25-493d-8bca-72a6cdff3bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmIcon</value>
      <webElementGuid>53b6ed9a-f9d6-4e4b-8781-529cbadff1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toggle</value>
      <webElementGuid>dbb05553-9afe-4682-ba44-d8cbce8cc668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_RadMenuUserOptions&quot;)/ul[@class=&quot;rmRootGroup rmToggleHandles rmHorizontal&quot;]/li[@class=&quot;rmItem rmFirst rmLast&quot;]/a[@class=&quot;rmLink rmRootLink&quot;]/span[@class=&quot;rmToggle&quot;]/span[@class=&quot;rmIcon&quot;]</value>
      <webElementGuid>abbbbfe3-3725-4e9f-a76f-29763a24bd41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_RadMenuUserOptions']/ul/li/a/span[2]/span</value>
      <webElementGuid>2038f1ba-176e-4752-b5ea-5848272d0ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C Hayes Software Systems'])[1]/following::span[2]</value>
      <webElementGuid>7f332ca1-612d-4ea0-9b65-39857f0cc0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[3]</value>
      <webElementGuid>6952c9c2-4a41-48cd-9511-61c6584f1f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::span[1]</value>
      <webElementGuid>3c1f719f-0afd-46db-b67c-7ef67d229c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Off'])[1]/preceding::span[2]</value>
      <webElementGuid>ae1f1e46-184a-4717-9197-a6d8ce4ebce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Toggle']/parent::*</value>
      <webElementGuid>3252cfda-2082-47b4-a7e2-58969e3b5de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>31c9c50d-c487-42a3-bea7-41eebcd0fc78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
