<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A A. MONTOYA ES_ctl00ContentPlaceHold_9ab308</name>
   <tag></tag>
   <elementGuidId>c2d1c623-9408-4ae2-8fae-ec5167184038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00_ctl14_ImageButtonProductDistributionOrCollectionReceipt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00_ctl14_ImageButtonProductDistributionOrCollectionReceipt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadGridStaff$ctl00$ctl06$StaffInventory$RadGridInventory$ctl00$ctl14$ImageButtonProductDistributionOrCollectionReceipt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00_ctl14_ImageButtonProductDistributionOrCollectionReceipt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Product Distribution Receipt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-action-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWeb/Images/Report.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Product Distribution Receipt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:OpenWindowNav('Reports/ReportsGateway.aspx?EntityTypeUID=3&amp;EntityUID=49967&amp;SiteUID=134&amp;FilterExpression=(iif(Tag == null, &quot;&quot;, Tag).ToString().ToUpper() = &quot;709217&quot;.ToUpper())&amp;InventoryHistoryUID=1153968&amp;ReportName=FullDistributionReceiptReport','RadWindowDistributionReceiptReport', 'Product Distribution Receipt'); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00_ctl14_ImageButtonProductDistributionOrCollectionReceipt&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00_ctl14_ImageButtonProductDistributionOrCollectionReceipt']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridStaff_ctl00_ctl06_StaffInventory_RadGridInventory_ctl00__5']/td[9]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[9]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
