<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Record</name>
   <tag></tag>
   <elementGuidId>7781760f-abbb-4785-b811-91a889f31096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_MainGrid_ctl00_ctl02_ctl00_InitInsertButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$MainGrid$ctl00$ctl02$ctl00$InitInsertButton','')&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>438a68fe-7aa6-447f-b9cc-2b70f1686b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$find('ctl00_ContentPlaceHolder1_MainGrid').get_batchEditingManager().addNewRecord('ctl00_ContentPlaceHolder1_MainGrid_ctl00'); return false;</value>
      <webElementGuid>0cf65114-b815-4fb0-85e7-ad7e4ec0eac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_MainGrid_ctl00_ctl02_ctl00_InitInsertButton</value>
      <webElementGuid>a7397b53-a0b9-429f-839d-836564bc070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>75b93a7b-17da-4225-901f-b0ad0c3773b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$MainGrid$ctl00$ctl02$ctl00$InitInsertButton','')</value>
      <webElementGuid>d85f54f9-ef4f-4ba5-b8a4-587a49df13a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>e4a45d1a-6f35-43d2-8eec-655e9816bc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_MainGrid_ctl00_ctl02_ctl00_InitInsertButton&quot;)</value>
      <webElementGuid>b879cbba-fa18-437f-bc48-bdb0be42ce51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_MainGrid_ctl00_ctl02_ctl00_InitInsertButton']</value>
      <webElementGuid>76bc9be9-4693-4b95-9c03-f67f87f49da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_MainGrid_ctl00']/thead/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>93279794-9091-46b1-b48e-d739639288d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Record')]</value>
      <webElementGuid>9c7b030e-7f59-4193-99ba-56de6771cc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Command item'])[2]/following::a[1]</value>
      <webElementGuid>aef3a49e-142d-4b89-bc88-9f447368b2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Command item'])[1]/following::a[1]</value>
      <webElementGuid>0bcf3293-2ceb-4e64-a6ce-0ecb2c2c7f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::a[1]</value>
      <webElementGuid>070b362a-bbf5-4512-8eea-06caaa00142a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Changes'])[1]/preceding::a[2]</value>
      <webElementGuid>9a2fdc2b-abee-44b4-9c96-f1217c60c47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Record']/parent::*</value>
      <webElementGuid>f6ad3a18-c693-464f-ad44-2c6eed9057fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$MainGrid$ctl00$ctl02$ctl00$InitInsertButton','')&quot;)]</value>
      <webElementGuid>dba51f7e-566d-4e83-8f6f-283c2a58a484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/a</value>
      <webElementGuid>55a4cebe-284b-4d1d-8f41-3ef157f38253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_MainGrid_ctl00_ctl02_ctl00_InitInsertButton' and @title = 'Add Record' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$MainGrid$ctl00$ctl02$ctl00$InitInsertButton&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Add Record' or . = 'Add Record')]</value>
      <webElementGuid>86489556-f5ec-47b4-b20a-2bbdd262a89b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
