<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Record</name>
   <tag></tag>
   <elementGuidId>37d84f8e-0eeb-4a82-a5e1-4cc47023926b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>962839ec-18d3-4657-924a-643cfed67a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord</value>
      <webElementGuid>33fc8812-d5f3-4596-9e1d-d96037f0f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridPurchasing$ctl00$ctl02$ctl00$LinkButtonAddRecord','')</value>
      <webElementGuid>65fa70ea-ed5d-4839-b967-484de2c0cf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>98b9ff3a-942e-42d9-b38f-75e42c1c1089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord&quot;)</value>
      <webElementGuid>2137b17f-6a79-40d8-91ff-40edd3bac32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord']</value>
      <webElementGuid>c43259c3-ae1b-4f14-a1eb-c47e74efb581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00']/thead/tr/td/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>bd73d97a-e087-468e-ba7f-3deff73f5b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Record')]</value>
      <webElementGuid>0f062c84-317c-4627-97c8-1fe73734e444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Off'])[1]/following::a[1]</value>
      <webElementGuid>2015bd56-91cf-4786-8736-e017dc547043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Inventory'])[1]/preceding::a[1]</value>
      <webElementGuid>ee7b95b9-ebdb-410d-95a8-d5bd5a02bc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Closed'])[1]/preceding::a[2]</value>
      <webElementGuid>32d0e57e-2504-4fa2-94e4-286df5ad86c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Record']/parent::*</value>
      <webElementGuid>bf733c1e-e473-4dae-a646-bbb71ab3b004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridPurchasing$ctl00$ctl02$ctl00$LinkButtonAddRecord','')&quot;)]</value>
      <webElementGuid>7f32b544-1c57-4b41-9d7e-860b40c97124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>1fadfa50-ca7c-4eda-8eea-3107c76643ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadGridPurchasing_ctl00_ctl02_ctl00_LinkButtonAddRecord' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$RadGridPurchasing$ctl00$ctl02$ctl00$LinkButtonAddRecord&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Add Record' or . = 'Add Record')]</value>
      <webElementGuid>2e98d02a-56a7-4c04-a54f-faf7d7a89741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
