<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Page Size arrow</name>
   <tag></tag>
   <elementGuidId>48fe45b9-9df0-4cf7-bbd8-85a83ad60a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fb5019b-7fbd-4369-a135-ba117bc38609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow</value>
      <webElementGuid>01414998-b305-49b0-9d5b-40243c4ec5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2db0bf7d-91dd-449e-8886-963d9fdb2afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow&quot;)</value>
      <webElementGuid>8a4c73b0-c07e-4d1f-b937-6c827b89279b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow']</value>
      <webElementGuid>eee24569-2ae9-4307-95b5-4add9bb0a56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>a0dc40a7-4f34-4fec-842e-a86693036c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'select')])[18]</value>
      <webElementGuid>be1396e1-01c5-4524-bef9-5ea8a5c3b92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PageSizeComboBox'])[2]/following::a[1]</value>
      <webElementGuid>8a9bb24a-cfb8-4eee-a1f4-7eded47b3f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page size:'])[2]/following::a[1]</value>
      <webElementGuid>70439471-a622-463c-8432-ac7632c60bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records to display.'])[2]/preceding::a[1]</value>
      <webElementGuid>ffad51a2-a52d-4bec-ac43-a2ed5db20bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/table/tfoot/tr/td/table/tbody/tr/td/div[4]/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>445d927d-dde2-430a-9616-bb5de3ddd52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl03_ctl01_PageSizeComboBox_Arrow' and (text() = 'select' or . = 'select')]</value>
      <webElementGuid>fb70633c-c691-4c0b-8d34-dc5ec53e917f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
