<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_select</name>
   <tag></tag>
   <elementGuidId>5c22def6-4f77-4efa-aefa-c19bc7c3e29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4eda954b-e757-465d-85e1-8136a83c3d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow</value>
      <webElementGuid>d25efa38-fbe7-4846-b714-0d1e288fd817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61704f09-32ba-4f15-a6ff-05c45f4ca054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow&quot;)</value>
      <webElementGuid>4cfb4ad6-ec8d-46a3-ad7d-49b8392df27c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow']</value>
      <webElementGuid>6bcd29fa-a57b-4e72-b286-01f7fa090ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>eb12f427-839f-4631-907c-5a048691dda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'select')])[12]</value>
      <webElementGuid>4fbbcc79-09a3-426a-b6a3-5c56db9ed392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Name:'])[1]/following::a[1]</value>
      <webElementGuid>0943e056-a4bb-4848-bfd0-f0166d4a05ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Filters'])[1]/following::a[1]</value>
      <webElementGuid>6770122b-affc-4c84-ae72-c631c60425c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check All'])[3]/preceding::a[1]</value>
      <webElementGuid>fe7fd533-8057-4f8d-b8f2-fac08950b8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#Pari01'])[3]/preceding::a[1]</value>
      <webElementGuid>b34e2b04-1678-421b-834f-850410bce514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>16cafd19-a700-44db-be84-7779f00c6153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Arrow' and (text() = 'select' or . = 'select')]</value>
      <webElementGuid>c5aa10ef-f69d-4449-91d4-45be55a6b408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
