<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tag 09890</name>
   <tag></tag>
   <elementGuidId>cd3b27e3-6558-4006-b34a-248e3b4a00df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78e858d3-7bbc-4b98-a07c-4fb2e86192e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:OpenWindowNav('Common/TagInfo.aspx?Tag=09890','RadWindowTagInfo'); return false;</value>
      <webElementGuid>a325cd8b-1ba3-4a5e-9678-383c3601a82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag</value>
      <webElementGuid>8346a51c-4daa-4f27-af20-660dc108c7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>09890</value>
      <webElementGuid>d9bc7210-2d09-4b2b-83c4-426b0d584b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridTags$ctl00$ctl04$LabelTag','')</value>
      <webElementGuid>29b13511-fa9a-4935-91d5-d3e2a4c10d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09890</value>
      <webElementGuid>63025ac5-46e4-4c92-ad86-576f7b1b34be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag&quot;)</value>
      <webElementGuid>621c8a28-6741-42e1-b1ae-e3f26742e1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag']</value>
      <webElementGuid>4b6c8c8c-9d53-4e95-8254-843b08938379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00__0']/td/a</value>
      <webElementGuid>89e1c187-4fe6-4cd6-b7a9-2bad6d061e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'09890')]</value>
      <webElementGuid>550effea-6b79-447b-91dd-c5929b2ee1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[18]/following::a[1]</value>
      <webElementGuid>a18aa599-6d48-463f-8686-e1d294bc663d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hewlett Packard Printer LaserJet 3052'])[1]/preceding::a[1]</value>
      <webElementGuid>8e175a62-07f8-445d-bea0-7a4c84981f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Use'])[4]/preceding::a[1]</value>
      <webElementGuid>f26ae7d1-c6ea-4e4c-82fc-471e5bacb942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='09890']/parent::*</value>
      <webElementGuid>d52b1f98-e99d-455e-ae68-8d3185ad7e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$ContentPlaceHolder1$RadGridTags$ctl00$ctl04$LabelTag','')&quot;)]</value>
      <webElementGuid>bdbaa9da-e043-4274-9994-307e3cfce8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/table/tbody/tr/td/a</value>
      <webElementGuid>3690e234-2b65-4661-adc4-28618b9c7846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ContentPlaceHolder1_RadGridTags_ctl00_ctl04_LabelTag' and @title = '09890' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$ContentPlaceHolder1$RadGridTags$ctl00$ctl04$LabelTag&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '09890' or . = '09890')]</value>
      <webElementGuid>9141fe27-eeda-485e-8338-23191864fb93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
