<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor_ctl00ContentPlaceHolder1ImageButtonGo</name>
   <tag></tag>
   <elementGuidId>65ae054e-5d78-49b5-b86d-5beed2397b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8b1a118-e628-454c-8a26-e0be56adac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>4823fdaa-e4a2-4ab5-9812-beac3bdf868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ImageButtonGo</value>
      <webElementGuid>8f85b7b8-bf09-4b80-bd37-37027462d30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      <webElementGuid>183facd2-cc9d-44ce-aec3-8349b3e2371f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a85414f4-887c-47fa-9dfe-e4b5ee21f3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>49d31a24-15b1-4da3-9867-7470942dad11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWEB/Images/go.gif</value>
      <webElementGuid>5199cc67-b758-440e-8057-78580e8971a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>47619d18-2154-4c81-83fc-cc0c323c1eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidateTagFilters();</value>
      <webElementGuid>81ff6c5a-fc56-4523-bea4-1184d5481c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ImageButtonGo&quot;)</value>
      <webElementGuid>c140bbb3-e5c7-4306-bd30-db7dbac5af02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      <webElementGuid>7e2f6336-9d66-468b-8a62-1226e9a7de3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_FiltersPanel']/div[2]/input[2]</value>
      <webElementGuid>f3a53225-a2f0-4aab-850e-f1b8a73ee272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input[2]</value>
      <webElementGuid>f3aba124-0974-439c-a0ea-a426897782ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$ImageButtonGo' and @id = 'ctl00_ContentPlaceHolder1_ImageButtonGo' and @title = 'Apply Filter(s)' and @src = '../App_Themes/TIPWEB/Images/go.gif' and @alt = 'Apply Filter(s)']</value>
      <webElementGuid>3d016845-b3fd-48f8-bc81-2f5e26e702a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
