<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Site Name_ctl00ContentPlaceHolder1Rad_6b4b20</name>
   <tag></tag>
   <elementGuidId>5733eeda-7cad-4b73-a010-dd1b3b9f4149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69fbf9fa-bfca-4fca-bc54-d8f1089172f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxSiteNameFilter</value>
      <webElementGuid>4d780bfb-9f48-428f-a2cf-3828c60ac74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de04d3c7-42cf-4912-a6c2-a3763f9d237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>f319cb1b-ebc9-4802-a821-115207d94c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input</value>
      <webElementGuid>0bbc5627-6535-453f-94f6-d5b62a7ce4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Please select:</value>
      <webElementGuid>861b332c-9298-40e0-a98f-5c93c21902fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>88292b1c-7791-407a-8916-557c80619525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a547dd03-7b83-48f3-affa-36539c4b7db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input&quot;)</value>
      <webElementGuid>c0b8a9e0-957b-417a-a6ff-3db77b4679ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      <webElementGuid>73caa5de-8a30-488a-840a-f7e993e6409f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter']/table/tbody/tr/td/input</value>
      <webElementGuid>0f7c2903-c1fe-472e-a2d0-a25210fd90e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>4b094834-a1e4-461e-8c8e-ef398e4bb4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxSiteNameFilter' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxSiteNameFilter_Input']</value>
      <webElementGuid>9216a816-ec45-4c1b-8918-842b2b43882f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
