<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_ctl00ContentPlaceHolder1RadPan_17416c</name>
   <tag></tag>
   <elementGuidId>4b2b2859-7001-47b6-880d-06a041400960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f55de53-55c8-40df-bc57-3a33738ff18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxStatusFilter</value>
      <webElementGuid>b5c10d08-4f5d-4196-9b08-45171aca1f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a2ed9bb-5623-455f-81a7-fc1687f9f7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rcbInput radPreventDecorate</value>
      <webElementGuid>6083939f-8111-4124-9594-d0c2bd8e2f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input</value>
      <webElementGuid>f567fad9-7537-4df4-add0-2b93382097c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Please select:</value>
      <webElementGuid>727986f9-401f-4368-8449-d296c5f632bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cadfa845-60cb-41a1-aea1-fbb183db1e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3b64428-2cb5-45de-8531-a55e21cace72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input&quot;)</value>
      <webElementGuid>622c45a5-3b87-481a-99fb-985e56fb4ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input']</value>
      <webElementGuid>6fbfdb2c-af06-47b3-937d-de76129108e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter']/table/tbody/tr/td/input</value>
      <webElementGuid>f9821d2d-762d-4a14-ba60-996308bb85a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>1e41d8b3-8d2d-40d2-a68f-4c21269391ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$RadPanelBarFilters$i0$RadComboBoxStatusFilter' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder1_RadPanelBarFilters_i0_RadComboBoxStatusFilter_Input']</value>
      <webElementGuid>68d88561-866c-4df6-b24c-8a68cf5bdbb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
