<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Page1</name>
   <tag></tag>
   <elementGuidId>5663077e-f395-4cd2-8eff-15662fa59ace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[9]/div/table/tfoot/tr/td/table/tbody/tr/td/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_RadGridTags_ctl00 > tfoot > tr.rgPager > td > table > tbody > tr > td.rgPagerCell.NextPrevAndNumeric > div.rgWrap.rgNumPart > a.rgCurrentPage > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84761680-c865-4aa3-9c5d-f0939120d0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e58a070c-7223-4769-a7b7-ab4c3dce8ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTags_ctl00&quot;)/tfoot[1]/tr[@class=&quot;rgPager&quot;]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;rgPagerCell NextPrevAndNumeric&quot;]/div[@class=&quot;rgWrap rgNumPart&quot;]/a[@class=&quot;rgCurrentPage&quot;]/span[1]</value>
      <webElementGuid>0042ea8b-d68f-4191-9005-c7d41296385b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00']/tfoot/tr/td/table/tbody/tr/td/div[2]/a/span</value>
      <webElementGuid>1c8aefc6-c05f-454c-b5b3-c4cec8706518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data pager'])[4]/following::span[1]</value>
      <webElementGuid>3ed6bbf7-390c-4228-9a96-2b9ab9a21d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data pager'])[3]/following::span[1]</value>
      <webElementGuid>59526493-c284-4cfb-bab6-c1ad9c8d3ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::span[10]</value>
      <webElementGuid>25b9ba10-2db3-4c69-b288-7cd584ff7982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page size:'])[2]/preceding::span[11]</value>
      <webElementGuid>86965671-ec70-40af-8685-64273ad9f2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/table/tfoot/tr/td/table/tbody/tr/td/div[2]/a/span</value>
      <webElementGuid>2f07b473-f87c-4ef7-a3f2-9952d25c6aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>5f39cf40-9d59-4446-9d7e-b938df65caf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
