<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Tag column</name>
   <tag></tag>
   <elementGuidId>fb69e418-6a35-4901-9a81-2afa04a363dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00']/thead/tr[2]/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.rgHeader.rgHeaderOver</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>a306698c-a3f7-4fb5-99a3-26dafe8be435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>d69c0649-6a4f-4e0d-a0d7-1ecbfec45ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgHeader rgHeaderOver</value>
      <webElementGuid>6428010b-10fb-4f84-be26-f83168eb9cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Drag to group or reorder</value>
      <webElementGuid>b81a8098-c3cc-44c3-9977-172a6a6f4261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tag</value>
      <webElementGuid>a4188533-1546-43d6-819e-0dd8a88dfdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_RadGridTags_ctl00&quot;)/thead[1]/tr[2]/th[@class=&quot;rgHeader rgHeaderOver&quot;]</value>
      <webElementGuid>9a130b9d-d49a-4314-a2b4-6929654b4667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_RadGridTags_ctl00']/thead/tr[2]/th</value>
      <webElementGuid>76e9df9c-effc-498e-8431-bfd7e399c2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Listing'])[1]/following::th[1]</value>
      <webElementGuid>d0b771ea-202c-4c8b-bcc9-9e5a17b90597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Depreciation Report'])[1]/following::th[1]</value>
      <webElementGuid>f3246810-e10f-41ab-88eb-4f5e05d61792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Seen Date'])[2]/preceding::th[1]</value>
      <webElementGuid>f5769cde-4591-4abe-af2a-bd13a3d7f924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/table/thead/tr[2]/th</value>
      <webElementGuid>05e49156-2554-427c-aa91-23d9643a3395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@title = 'Drag to group or reorder' and (text() = 'Tag' or . = 'Tag')]</value>
      <webElementGuid>0a2fcdae-d415-4f0f-b7a3-3ceb31c75207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
