<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go</name>
   <tag></tag>
   <elementGuidId>baddfea3-c936-4b42-b92f-9e47d9f5287c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>161fd733-88a6-4e71-857a-b8991b76f977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ce5bbd0e-fe53-429c-9a06-4e1346f7c042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ImageButtonGo</value>
      <webElementGuid>7de0fe37-c1c4-4511-881c-afb28a29b54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ImageButtonGo</value>
      <webElementGuid>98e4dee0-0942-462b-8d5b-54aa072a8e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>cd898f17-d33c-431d-9bbb-32c12c735028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>b1b3ec6f-14b4-43db-9c86-cf948b629016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../App_Themes/TIPWEB/Images/go.gif</value>
      <webElementGuid>5b009394-2028-40bf-83e6-5503ca570422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apply Filter(s)</value>
      <webElementGuid>b5d0c666-8652-4184-8e08-85bc2a18e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidateFilters();WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$ImageButtonGo&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>24f9d26a-83ba-46c7-b2a6-71acbcd2bafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ImageButtonGo&quot;)</value>
      <webElementGuid>bc2b5c1d-212c-4cd3-b022-e0d77fccc379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ImageButtonGo']</value>
      <webElementGuid>136c6eb4-7381-40ba-8e41-638a5abb2f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_FiltersPanel']/div/input[2]</value>
      <webElementGuid>92c4cbf6-1753-47fb-97d4-b40079b1fe45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>5b997bcf-3c66-4445-b2fe-6e8d3aa3b307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$ImageButtonGo' and @id = 'ctl00_ContentPlaceHolder1_ImageButtonGo' and @title = 'Apply Filter(s)' and @src = '../App_Themes/TIPWEB/Images/go.gif' and @alt = 'Apply Filter(s)']</value>
      <webElementGuid>eb2b8b84-19f0-4db6-a027-55c96fab02fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
